#pragma once

#define LINKET_LATENT_DIM 16

#define LINKET_BLOCK_SIZE 8

#define LINKET_TILE_SIZE 40

#define LINKET_BLOCKS_PER_TILE ((LINKET_TILE_SIZE * LINKET_TILE_SIZE) / (LINKET_BLOCK_SIZE * LINKET_BLOCK_SIZE))
