#pragma once

#define LINKET_EPSILON 1.0e-6F

#define LINKET_LATENT_DIM 12

#define LINKET_BYTES_PER_LATENT 12

#define LINKET_BLOCK_SIZE 8

#define LINKET_TILE_SIZE 80

#define LINKET_BLOCKS_PER_TILE ((LINKET_TILE_SIZE * LINKET_TILE_SIZE) / (LINKET_BLOCK_SIZE * LINKET_BLOCK_SIZE))

#define LINKET_BYTES_PER_TILE (LINKET_BLOCKS_PER_TILE * LINKET_BYTES_PER_LATENT)
